config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/services' => 'pages#services'
  get '/gallery' => 'pages#gallery'

  get '/contact',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
        :subject => "Need Information about Siri Events",
        :to => "bhanuandrajula@gmail.com",
        :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your interest on Siri Events. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def services
    @title = "Services"
  end

  def gallery
    @title = "Gallery"
  end

  def contact
    @title = "Contact"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Return a title on a per-page basis.
  def title
    base_title = "Siri Events"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end

  def logo
    image_tag("SiriEvents.png", :alt => "Siri Events", :width=>"180" ,:height=>"100", :class => "round")
  end

  def fb
    image_tag("fb.png", :alt => "FB", :width=>"30" ,:height=>"40", :class => "round")
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
      <div>
        <a href="#" data-dismiss="alert">×</a>
        <%= value %>
      </div>
  <% end %>
</div>

app/views/contacts/new.html.erb

<div align="center">
  <h3>Send A message to Us</h3>

  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
      <%= f.input :name, :required => true %>
      <%= f.input :email, :required => true %>
      <%= f.input :message, :as => :text, :required => true %>
      <div class= "hidden">
        <%= f.input :nickname, :hint => 'Leave this field blank!' %>
      </div>
      <div>
        </br>
        <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
      </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
  <ftid>
    © COPYRIGHT 2014        SIRI EVENTS
  </ftid>

</div>

app/views/layouts/_header.html.erb
<div id="header">

   <%= link_to logo,root_url %>

  <ul class="navigation round">
    <li><%= link_to "Facebook", 'https://www.facebook.com/siris' %></li>
    <li><%= link_to "Twitter", 'https://twitter.com/sirievents' %></li>
    <li><%= link_to "Google+", 'https://plus.google.com/106213346933467639263/about' %></li>
    <li><%= link_to "Videos", 'https://www.youtube.com/results?search_query=sirisha+bavireddy' %></li>
  </ul>

  <ul class="menu-bar">
  <li><%= link_to "Home", root_url %></li>
  <li><%= link_to "Services", services_url %></li>
  <li><%= link_to "Gallery", gallery_url %></li>
  <li><%= link_to "Contact", contact_url %></li>
  </ul>



</div>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title%></title>
  <%= render 'layouts/stylesheets' %>
</head>
<body>

<div class="container">
  <%= render 'layouts/header' %>


  <%= yield %>

</div>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/contact.html.erb
<p>
  This is the contact page for the
  <a href="http://www.sirievents.com">Siri Events</a>
</p>

app/views/pages/create.html.erb
<div>
  <% flash.each do |key, value| %>
      <div>
        <a href="#" data-dismiss="alert">×</a>
        <%= value %>
      </div>
  <% end %>
</div>

app/views/pages/gallery.html.erb
<p>
  This is the gallery page for the
  <a href="http://www.sirievents.com">Siri Events</a>
</p>

app/views/pages/home.html.erb
<p>Siri events is a boutique event planning & decorator service in Dallas Fortworth area.
    Sirisha Bavireddy has an engineering background and while helping friends and family organize
    weddings and parties she found her true calling and started Siri Events in 2003.
    Sirisha brings in her impeccable attention to detail and passion to create sophisticated
    and memorable events. Each event is unique and tailored to client's vision.</p>

app/views/pages/new.html.erb

<div align="center">
  <h3>Send A message to Us</h3>

  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
      <%= f.input :name, :required => true %>
      <%= f.input :email, :required => true %>
      <%= f.input :message, :as => :text, :required => true %>
      <div class= "hidden">
        <%= f.input :nickname, :hint => 'Leave this field blank!' %>
      </div>
      <div>
        </br>
        <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
      </div>
  <% end %>
</div>

app/views/pages/services.html.erb
<p>
  From start to finish, Siri Events works closely with each client to ensure the success of the event. Here are just a few things we do:



  * event design & installation

  * budgeting

  * venue recommendations & visits

  * vendor managemen
</p>